### ISSUE TITLE
[QUESTION] This module is for non-Trezor (model T) HW wallets?

### ISSUE THREAD

**Issue by doolio** [rendaw/trezor-gpg-pinentry-tk#3]
Reading the trezor-agent documentation and I just want to confirm that your module is not for use with the Trezor model T (as it offers on device PIN entry) but with the other HW wallets supported by trezor-agent. Your module simply provides the Trezor model T like pin entry to these other devices, right? TIA. 

(Sorry if this a dumb question)

**Comment by rendaw** [comment]
Hey! No, not at all!

Yeah, this is just for the touchscreen-less wallets. TBH I think I made this before the T came out. The (classic?) Trezor shows a grid of numbers, and this provides a screen keypad that matches the layout.  IIRC the normal gpg pinentry was really unintuitive for this.

(Feel free to re-open if there's more to talk about)

**Comment by doolio** [comment]
Ok, great. Thanks for getting back to me so quickly.
